/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as PricingImport } from './routes/pricing'
import { Route as LoginImport } from './routes/login'
import { Route as CreateFreeImport } from './routes/create-free'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as CreateFreeIndexImport } from './routes/create-free/index'
import { Route as CreateFreePreviewImport } from './routes/create-free/preview'
import { Route as CCIdImport } from './routes/c.$cId'
import { Route as AuthenticatedUUIdImport } from './routes/_authenticated/u.$uId'
import { Route as AuthenticatedUUIdCCIdEditImport } from './routes/_authenticated/u.$uId.c.$cId.edit'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const PricingRoute = PricingImport.update({
  path: '/pricing',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const CreateFreeRoute = CreateFreeImport.update({
  path: '/create-free',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CreateFreeIndexRoute = CreateFreeIndexImport.update({
  path: '/',
  getParentRoute: () => CreateFreeRoute,
} as any)

const CreateFreePreviewRoute = CreateFreePreviewImport.update({
  path: '/preview',
  getParentRoute: () => CreateFreeRoute,
} as any)

const CCIdRoute = CCIdImport.update({
  path: '/c/$cId',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedUUIdRoute = AuthenticatedUUIdImport.update({
  path: '/u/$uId',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedUUIdCCIdEditRoute = AuthenticatedUUIdCCIdEditImport.update({
  path: '/c/$cId/edit',
  getParentRoute: () => AuthenticatedUUIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/create-free': {
      id: '/create-free'
      path: '/create-free'
      fullPath: '/create-free'
      preLoaderRoute: typeof CreateFreeImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/c/$cId': {
      id: '/c/$cId'
      path: '/c/$cId'
      fullPath: '/c/$cId'
      preLoaderRoute: typeof CCIdImport
      parentRoute: typeof rootRoute
    }
    '/create-free/preview': {
      id: '/create-free/preview'
      path: '/preview'
      fullPath: '/create-free/preview'
      preLoaderRoute: typeof CreateFreePreviewImport
      parentRoute: typeof CreateFreeImport
    }
    '/create-free/': {
      id: '/create-free/'
      path: '/'
      fullPath: '/create-free/'
      preLoaderRoute: typeof CreateFreeIndexImport
      parentRoute: typeof CreateFreeImport
    }
    '/_authenticated/u/$uId': {
      id: '/_authenticated/u/$uId'
      path: '/u/$uId'
      fullPath: '/u/$uId'
      preLoaderRoute: typeof AuthenticatedUUIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/u/$uId/c/$cId/edit': {
      id: '/_authenticated/u/$uId/c/$cId/edit'
      path: '/c/$cId/edit'
      fullPath: '/u/$uId/c/$cId/edit'
      preLoaderRoute: typeof AuthenticatedUUIdCCIdEditImport
      parentRoute: typeof AuthenticatedUUIdImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedUUIdRouteChildren {
  AuthenticatedUUIdCCIdEditRoute: typeof AuthenticatedUUIdCCIdEditRoute
}

const AuthenticatedUUIdRouteChildren: AuthenticatedUUIdRouteChildren = {
  AuthenticatedUUIdCCIdEditRoute: AuthenticatedUUIdCCIdEditRoute,
}

const AuthenticatedUUIdRouteWithChildren =
  AuthenticatedUUIdRoute._addFileChildren(AuthenticatedUUIdRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedUUIdRoute: typeof AuthenticatedUUIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedUUIdRoute: AuthenticatedUUIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CreateFreeRouteChildren {
  CreateFreePreviewRoute: typeof CreateFreePreviewRoute
  CreateFreeIndexRoute: typeof CreateFreeIndexRoute
}

const CreateFreeRouteChildren: CreateFreeRouteChildren = {
  CreateFreePreviewRoute: CreateFreePreviewRoute,
  CreateFreeIndexRoute: CreateFreeIndexRoute,
}

const CreateFreeRouteWithChildren = CreateFreeRoute._addFileChildren(
  CreateFreeRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/create-free': typeof CreateFreeRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/sign-up': typeof SignUpRoute
  '/c/$cId': typeof CCIdRoute
  '/create-free/preview': typeof CreateFreePreviewRoute
  '/create-free/': typeof CreateFreeIndexRoute
  '/u/$uId': typeof AuthenticatedUUIdRouteWithChildren
  '/u/$uId/c/$cId/edit': typeof AuthenticatedUUIdCCIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/sign-up': typeof SignUpRoute
  '/c/$cId': typeof CCIdRoute
  '/create-free/preview': typeof CreateFreePreviewRoute
  '/create-free': typeof CreateFreeIndexRoute
  '/u/$uId': typeof AuthenticatedUUIdRouteWithChildren
  '/u/$uId/c/$cId/edit': typeof AuthenticatedUUIdCCIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/create-free': typeof CreateFreeRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/sign-up': typeof SignUpRoute
  '/c/$cId': typeof CCIdRoute
  '/create-free/preview': typeof CreateFreePreviewRoute
  '/create-free/': typeof CreateFreeIndexRoute
  '/_authenticated/u/$uId': typeof AuthenticatedUUIdRouteWithChildren
  '/_authenticated/u/$uId/c/$cId/edit': typeof AuthenticatedUUIdCCIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/create-free'
    | '/login'
    | '/pricing'
    | '/sign-up'
    | '/c/$cId'
    | '/create-free/preview'
    | '/create-free/'
    | '/u/$uId'
    | '/u/$uId/c/$cId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/pricing'
    | '/sign-up'
    | '/c/$cId'
    | '/create-free/preview'
    | '/create-free'
    | '/u/$uId'
    | '/u/$uId/c/$cId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/create-free'
    | '/login'
    | '/pricing'
    | '/sign-up'
    | '/c/$cId'
    | '/create-free/preview'
    | '/create-free/'
    | '/_authenticated/u/$uId'
    | '/_authenticated/u/$uId/c/$cId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CreateFreeRoute: typeof CreateFreeRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignUpRoute: typeof SignUpRoute
  CCIdRoute: typeof CCIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CreateFreeRoute: CreateFreeRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignUpRoute: SignUpRoute,
  CCIdRoute: CCIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/create-free",
        "/login",
        "/pricing",
        "/sign-up",
        "/c/$cId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/u/$uId"
      ]
    },
    "/create-free": {
      "filePath": "create-free.tsx",
      "children": [
        "/create-free/preview",
        "/create-free/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/pricing": {
      "filePath": "pricing.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/c/$cId": {
      "filePath": "c.$cId.tsx"
    },
    "/create-free/preview": {
      "filePath": "create-free/preview.tsx",
      "parent": "/create-free"
    },
    "/create-free/": {
      "filePath": "create-free/index.tsx",
      "parent": "/create-free"
    },
    "/_authenticated/u/$uId": {
      "filePath": "_authenticated/u.$uId.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/u/$uId/c/$cId/edit"
      ]
    },
    "/_authenticated/u/$uId/c/$cId/edit": {
      "filePath": "_authenticated/u.$uId.c.$cId.edit.tsx",
      "parent": "/_authenticated/u/$uId"
    }
  }
}
ROUTE_MANIFEST_END */
